# usage

# model=qwen_3.6_28b_reap_20
# model=glm_4.7_flash_reap
# source start_server_prod.sh && start_server $model

models:

# Qwen 3 Coder
  Qwen3-Coder-Next-REAP-40B-A3B.i1-IQ3_M_mradermacher.gguf:
    file: Qwen3-Coder-Next-REAP-40B-A3B.i1-IQ3_M_mradermacher.gguf
    note: ...
    ctx_k: 64
    gpu_layers: 99
    cpu_moe: 7
    batch : 1024
    ubatch: 256
    spec_type: none
    pi_agent_model: >
      { 
          "_test": "✔️ Very good",
          "_speed": "22 t/s",
          "id": "Qwen3-Coder-Next-REAP-40B-A3B.i1-IQ3_M_mradermacher.gguf",
          "name": "Qwen3-Coder-Next REAP-40B-A3B i1 IQ3_M (mradermacher) 64k",
          "alias": "mradermacher/Qwen3-Coder-Next REAP-40B-A3B i1 IQ3_M [64k]",
          "contextWindow": 65536,
          "maxTokens": 4096,
          "reasoning": true
      },

  Qwen_3_Coder_UD-Q3_K_XL_(Unsloth)_96k:
    file: Qwen3-Coder-30B-A3B-Instruct-UD-Q3_K_XL_unsloth.gguf
    note: ...
    ctx_k: 96
    gpu_layers: 99
    cpu_moe: 0
    batch : 1024
    ubatch: 256
    spec_type: none
    pi_agent_model: >
      { 
          "_test": "??",
          "_speed": "? t/s",
          "id": "Qwen3-Coder-30B-A3B-Instruct-UD-Q3_K_XL_unsloth.gguf",
          "alias": "Unsloth/Qwen3 Coder UD-Q3_K_XL [96k]",
          "contextWindow": 98304,
          "maxTokens": 4096,
          "reasoning": true
      },
  Qwen_3_Coder_REAP-25B_(bartowski)_64k:
    file: Qwen3-Coder-REAP-25B-A3B-Q4_K_M_bartowski.gguf
    note: ...
    ctx_k: 64
    gpu_layers: 99
    cpu_moe: 7
    batch : 1024
    ubatch: 256
    jinja: 0
    #spec_type: ngram-simple
    #spec_ngram_simple_size_n: 16
    #spec_ngram_simple_size_m: 16
    #spec_ngram_simple_min_hits: 1
    spec_type: none
    pi_agent_model: >
      { 
          "_test": "??",
          "_speed": "? t/s",
          "id": "Qwen3-Coder-REAP-25B-A3B-Q4_K_M_bartowski.gguf",
          "alias": "bartowski/Qwen3 Coder 25B-A3B Q4_K_M [64k]",
          "name": "Qwen_3_Coder_REAP-25B_(bartowski)_64k",
          "contextWindow": 65536,
          "maxTokens": 4096,
          "reasoning": true
      },

  Qwen3-Coder-30B-A3B-Instruct-IQ4_XS_unsloth:
    file: Qwen3-Coder-30B-A3B-Instruct-IQ4_XS_unsloth.gguf
    note: ...
    ctx_k: 96
    gpu_layers: 99
    cpu_moe: 8
    batch : 1024
    ubatch: 256
    jinja: 0
    #spec_type: ngram-simple
    #spec_ngram_simple_size_n: 16
    #spec_ngram_simple_size_m: 16
    #spec_ngram_simple_min_hits: 1
    spec_type: none
    pi_agent_model: >
      { 
          "_test": "??",
          "_speed": "? t/s",
          "id": "Qwen3-Coder-30B-A3B-Instruct-IQ4_XS_unsloth.gguf",
          "alias": "Unsloth/Qwen3-Coder 30B-A3B Instruct IQ4_XS [96k]",
          "contextWindow": 98304,
          "maxTokens": 4096,
          "reasoning": true
      },


# Qwen 3.5 27B
  Qwen_3.5_27B_(Unsloth)_48k:
    file: Qwen3.5-27B-IQ4_XS_unsloth.gguf
    ctx_k: 48
    gpu_layers: 99
    cpu_moe: 0
    batch: 2048
    ubatch: 1024
    spec_type: none
    jinja: 1
    pi_agent_model: >
      { 
         "_test": "Slooooow",
         "_speed": "16 t/s",
          "id": "Qwen3.5-27B-IQ4_XS_unsloth.gguf",
          "name": "Qwen 3.5 27B (Unsloth) 48k",
          "contextWindow": 49152,
          "maxTokens": 2048,
          "reasoning": true,
          "input": [ "text", "image" ]
      },

# Qwen 3.6 27B
  Qwen3.6-27B-Cerebellum-v5-Q2_K_(deucebucket)_96k:
    file: Qwen3.6-27B-Cerebellum-v5-Q2_K_deucebucket.gguf
    ctx_k: 96
    gpu_layers: 99
    cpu_moe: 0
    batch: 1024
    ubatch: 512
    spec_type: none
    jinja: 0
    pi_agent_model: >
      { 
         "_test": "🥇 Ottimo!",
         "_speed": "17 t/s",
          "id": "Qwen3.6-27B-Cerebellum-v5-Q2_K_deucebucket.gguf",
          "name": "Qwen3.6-27B Cerebellum-v5 Q2_K (deucebucket) 96k",
          "contextWindow": 96000,
          "maxTokens": 4096,
          "reasoning": true,
          "input": [ "text", "image" ]
      },

  Qwen3.6-27B-Cerebellum-v5-Q2_K_(deucebucket)_SPEC__96k:
    file: Qwen3.6-27B-Cerebellum-v5-Q2_K_deucebucket.gguf
    ctx_k: 128
    gpu_layers: 99
    cpu_moe: 0
    batch: 1024
    ubatch: 512
    spec_type: ngram-simple
    spec_ngram_simple_size_n: 8
    spec_ngram_simple_size_m: 8
    spec_ngram_simple_min_hits: 1
    jinja: 0
    pi_agent_model: >
      { 
         "_test": "🥇 Ottimo!",
         "_speed": "20 t/s",
          "id": "Qwen3.6-27B-Cerebellum-v5-Q2_K_deucebucket.gguf",
          "name": "Qwen3.6-27B Cerebellum-v5 Q2_K (deucebucket) 128k",
          "contextWindow": 128000,
          "maxTokens": 4096,
          "reasoning": true,
          "input": [ "text", "image" ]
      },

  Qwen3.6-27B_IQ4_XS_(unsloth)_64k:
    file: Qwen3.6-27B-IQ4_XS_unsloth.gguf
    ctx_k: 64
    gpu_layers: 99
    cpu_moe: 0
    batch: 1024
    ubatch: 512
    spec_type: none
    jinja: 0
    pi_agent_model: >
      { 
         "_test": "?",
         "_speed": "? t/s",
          "id": "Qwen3.6-27B-IQ4_XS_unsloth.gguf",
          "name": "Qwen3.6 27B IQ4_XS (Unsloth) 64k",
          "contextWindow": 64000,
          "maxTokens": 4096,
          "reasoning": true,
          "input": [ "text", "image" ]
      },


  Qwen3.6-27B_IQ4_XS_(unsloth)_80k_spec:
    file: Qwen3.6-27B-IQ4_XS_unsloth.gguf
    ctx_k: 80
    gpu_layers: 99
    cpu_moe: 0
    batch: 1024
    ubatch: 256
    spec_type: ngram-simple
    spec_ngram_simple_size_n: 8
    spec_ngram_simple_size_m: 16
    spec_ngram_simple_min_hits: 1
    jinja: 0
    pi_agent_model: >
      { 
         "_test": "?",
         "_speed": "? t/s",
          "id": "Qwen3.6-27B-IQ4_XS_unsloth.gguf",
          "alias": "Unsloth/Qwen3.6 27B IQ4_XS [64k]",
          "name": "Qwen3.6 27B IQ4_XS (Unsloth) 64k",
          "contextWindow": 64000,
          "maxTokens": 4096,
          "reasoning": true,
          "input": [ "text", "image" ]
      },


# Qwen 3.6 35B A3B
  Qwen_3.6_28b_reap_20_(barozp)_64k:
    file: Qwen3.6-28B-REAP20-A3B-Q4_K_M_barozp.gguf
    alias: Qwen 3.6 28B-REAP20-A3B Q4_K_M (by barozp) [64k]
    ctx_k: 64
    gpu_layers: 99
    cpu_moe: 4
    batch: 1024
    ubatch: 512
    spec_type: none
    jinja: 0
    pi_agent_model: >
      { 
         "_test": "✔️ Really good",
         "_speed": "35 t/s",
          "id": "Qwen3.6-28B-REAP20-A3B-Q4_K_M_barozp.gguf",
          "name": "Qwen 3.6 28B REAP20 (barozp) 64k",
          "alias": "barozp/Qwen 3.6 28B REAP20 A3B [64k]",
          "contextWindow": 64000,
          "maxTokens": 4096,
          "reasoning": true,
          "input": [ "text", "image" ]
      },
  Qwen_3.6_28b_reap_20_(barozp)_96k:
    file: Qwen3.6-28B-REAP20-A3B-Q4_K_M_barozp.gguf
    ctx_k: 96
    gpu_layers: -1
    cpu_moe: 4
    batch: 1024
    ubatch: 512
    spec_type: none
    jinja: 0
    pi_agent_model: >
      { 
         "_test": "Really good",
         "_speed": "35 t/s",
          "id": "Qwen3.6-28B-REAP20-A3B-Q4_K_M_barozp.gguf",
          "name": "Qwen 3.6 28B REAP20 (barozp) 96k",
          "contextWindow": 98304,
          "maxTokens": 4096,
          "reasoning": true,
          "input": [ "text", "image" ]
      },

  Qwen_3.6_35B_A3B_Genesis_v3_APEX_(luffythefox)_128k:
    file: Qwen3.6-35B-A3B-Un-Genesis-V3-APEX_luffythefox.gguf
    note: Can use 96K with MOE 3
    note_2: With ngram-simple 4/4 is super fast in tests but slow in reality
    ctx_k: 128
    gpu_layers: -1
    cpu_moe: 4
    batch : 2048
    ubatch: 512
    spec_type: none
    pi_agent_model: >
      { 
          "_test": "✔️ OK, chatty with open ended questions",
          "_speed": "30 t/s",
          "id": "Qwen3.6-35B-A3B-Un-Genesis-V3-APEX_luffythefox.gguf",
          "name": "Qwen 3.6 35B Genesis v3 APEX (luffythefox) 128k",
          "contextWindow": 131072,
          "_contextWindow": 96000,
          "maxTokens": 4096,
          "reasoning": true
      },
  
# Qwopus



# Gemma 4 26B  
  Gemma4-26B-A4B-QAT-Unc-Balanced-Q4_K_M_hauhaucs.gguf:
    file: Gemma4-26B-A4B-QAT-Unc-Balanced-Q4_K_M_hauhaucs.gguf
    ctx_k: 128
    gpu_layers: 99
    cpu_moe: 4
    batch: 1024
    ubatch: 512
    spec_type: none 
    pi_agent_model: >
       { 
            "_test": "???",
            "id": "Gemma4-26B-A4B-QAT-Unc-Balanced-Q4_K_M_hauhaucs.gguf",
            "name": "Gemma4-26B-A4B-QAT-Unc-Balanced-Q4_K_M_hauhaucs.gguf",
            "contextWindow": 131072,
            "maxTokens": 8192,
            "reasoning": true
        },

  Gemma-4-26B-Q4_0_(Google)_64k:
    speed: 0 t/s
    file: Gemma-4-26B_Q4_0-it_google.gguf
    ctx_k: 64
    gpu_layers: -1
    cpu_moe: 0
    batch: 2048
    ubatch: 1024
    spec_type: none 
    pi_agent_model: >
       { 
            "_test": "???",
            "id": "Gemma-4-26B_Q4_0-it_google.gguf",
            "name": "Gemma4 26B 64K - Q4_0 (by Google)",
            "contextWindow": 64000,
            "maxTokens": 4096,
            "reasoning": true
        },
  Gemma-4-26B-Q4_0_(Google)_128k:
    speed: 43 t/s
    file: Gemma-4-26B_Q4_0-it_google.gguf
    ctx_k: 128
    gpu_layers: -1
    cpu_moe: 1
    batch: 1024
    ubatch: 512
    spec_type: none 
    pi_agent_model: >
       { 
            "_test": "???",
            "id": "Gemma-4-26B_Q4_0-it_google.gguf",
            "name": "Gemma4 26B 128K - Q4_0 (by Google)",
            "contextWindow": 131072,
            "maxTokens": 4096,
            "reasoning": true
        },
  Gemma-4-26B-Q4_0_(Google)_256k:
    speed: "?? t/s"
    file: Gemma-4-26B_Q4_0-it_google.gguf
    ctx_k: 256
    gpu_layers: -1
    cpu_moe: 3
    batch: 1024
    ubatch: 256
    spec_type: none 
    pi_agent_model: >
       { 
            "_test": "???",
            "id": "Gemma-4-26B_Q4_0-it_google.gguf",
            "name": "Gemma4 26B 256K - Q4_0 (by Google)",
            "contextWindow": 131072,
            "maxTokens": 4096,
            "reasoning": true
        },
  Gemma-4_26B_MXFP4_(Noctrex)_128k:
    speed: 33 t/s
    file: Gemma-4-26B-A4B-it-MXFP4_MOE_noctrex.gguf
    ctx_k: 128
    gpu_layers: 99
    cpu_moe: 3
    batch: 1024
    ubatch: 512
    spec_type: none 
    pi_agent_model: >
      { 
        "_test": "Good",
        "_sped": "? t/s",
        "id": "Gemma-4-26B-A4B-it-MXFP4_MOE_noctrex.gguf",
        "name": "Gemma4 26B - MXFP4 (by Noctrex) 128K",
        "contextWindow": 131072,
        "maxTokens": 4096,
        "reasoning": true
      },

  Gemma-4-26B-UD-IQ4_NL_(Unsloth)_64k:
    speed: 45 t/s
    file: Gemma-4-26B-A4B-it-UD-IQ4_NL_unsloth.gguf
    ctx_k: 64
    gpu_layers: -1
    cpu_moe: 0
    batch: 1024
    ubatch: 256
    spec_type: none 
    pi_agent_model: >
      { 
        "_test": "???",
        "id": "Gemma-4-26B-A4B-it-UD-IQ4_NL_unsloth.gguf",
        "name": "Gemma4 26B - UD-IQ4_NL (by Unsloth) 64K",
        "contextWindow": 6500,
        "maxTokens": 4096,
        "reasoning": true
      },
  Gemma-4-26B-UD-IQ4_NL_(Unsloth)_160k:
    speed: n.a.
    file: Gemma-4-26B-A4B-it-UD-IQ4_NL_unsloth.gguf
    ctx_k: 160
    gpu_layers: -1
    cpu_moe: 1
    batch: 1024
    ubatch: 256
    spec_type: none 
    pi_agent_model: >
      { 
        "_test": "???",
        "id": "Gemma-4-26B-A4B-it-UD-IQ4_NL_unsloth.gguf",
        "name": "Gemma4 26B - UD-IQ4_NL (by Unsloth) 160K",
        "contextWindow": 163840,
        "maxTokens": 4096,
        "reasoning": true
      },
  Gemma-4-26B-UD-IQ4_NL_(Unsloth)_SPEC_160k:
    speed: n.a.
    file: Gemma-4-26B-A4B-it-UD-IQ4_NL_unsloth.gguf
    ctx_k: 160
    gpu_layers: -1
    cpu_moe: 1
    batch: 1024
    ubatch: 256
    _spec_type: none 
    spec_type: ngram-simple
    spec_ngram_simple_size_m: 4
    spec_ngram_simple_size_n: 4
    spec_ngram_simple_min_hits: 1
    pi_agent_model: >
      { 
        "_test": "???",
        "id": "Gemma-4-26B-A4B-it-UD-IQ4_NL_unsloth.gguf",
        "name": "Gemma4 26B - UD-IQ4_NL (by Unsloth) 160K",
        "contextWindow": 163840,
        "maxTokens": 4096,
        "reasoning": true
      },
  
# GLM 4.7 Flash
  GLM_4.7-Flash_UD-Q3_K_XL_(Unsloth)_128k:
    file: GLM-4.7-Flash-UD-Q3_K_XL_unsloth.gguf
    ctx_k: 128
    gpu_layers: 45
    cpu_moe: 2
    batch: 1024
    ubatch: 256
    spec_type: none
    jinja: 1
    pi_agent_model: >
      { 
        "_test": "?",
        "_speed": "? t/s",
        "id": "GLM-4.7-Flash-UD-Q3_K_XL_unsloth.gguf",
        "name": "GLM 4.7 Flash UD Q3_K_XL (Unsloth) 128K",
        "contextWindow": 131072,
        "maxTokens": 4096,
        "reasoning": true
      },

  GLM_4.7-Flash_(gaionaus)_128k:
    file: GLM-4.7-flash-Q4_K_M_gaionaus.gguf
    ctx_k: 128
    gpu_layers: -1
    cpu_moe: 2
    batch: 1024
    ubatch: 256
    spec_type: none
    pi_agent_model: >
      { 
        "_test": "?",
        "id": "GLM-4.7-flash-Q4_K_M_gaionaus.gguf",
        "name": "GLM 4.7 Flash Q4_K_M (by gaionaus) 128K",
        "contextWindow": 131072,
        "maxTokens": 4096,
        "reasoning": true
      },

# GPT OSS 20B
  GPT-OSS-20B_20b_UD-Q8_K_XL:
    file: GPT-OSS-20b-UD-Q8_K_XL_unsloth.gguf
    ctx_k: 128
    gpu_layers: 99
    cpu_moe: 0
    batch: 2048
    ubatch: 1024
    spec_type: none
    pi_agent_model: >
        { 
            "_test": "?",
            "id": "GPT-OSS-20b-UD-Q8_K_XL_unsloth.gguf",
            "name": "GPT OSS 20B UD Q8_K_XL (by Unsloth)",
            "contextWindow": 131072,
            "maxTokens": 2048,
            "reasoning": true
        },

  GPT-OSS-20B_20b_UD-Q6_K_XL:
    file: GPT-OSS-20b-UD-Q6_K_XL_unsloth.gguf
    ctx_k: 128
    gpu_layers: -1
    cpu_moe: 0
    batch: 2048
    ubatch: 384
    spec_type: none
    pi_agent_model: >
        { 
            "_test": "?",
            "id": "GPT-OSS-20b-UD-Q6_K_XL_unsloth.gguf",
            "name": "GPT OSS 20B UD Q6_K_XL (by Unsloth)",
            "contextWindow": 131072,
            "maxTokens": 2048,
            "reasoning": true
        },

  GPT-OSS-20B_UD-Q8_K_XL_UD-Q8_K_XL-N-gram_1:
    file: GPT-OSS-20b-UD-Q8_K_XL_unsloth.gguf
    ctx_k: 64
    gpu_layers: -1
    cpu_moe: 0
    batch: 1024
    ubatch: 256
    spec_type: ngram-simple
    spec_ngram_simple_size_m: 4
    spec_ngram_simple_size_n: 6
    spec_ngram_simple_min_hits: 1
    pi_agent_model: >
        { 
            "_test": "?",
            "id": "GPT-OSS-20b-UD-Q8_K_XL_unsloth.gguf",
            "name": "GPT OSS 20B UD Q8_K_XL",            
            "contextWindow": 65536,
            "maxTokens": 4096,
            "reasoning": true
        },

  GPT-OSS-20B_IQ4_NL:
    file: OpenAI-20B-NEO-CODE2-Plus-Uncensored-IQ4_NL_davidau.gguf
    ctx_k: 128
    gpu_layers: -1
    cpu_moe: 0
    batch: 2048
    ubatch: 256
    spec_type: none      

    #spec_type="ngram-simple"
    #spec_ngram_simple_size_m=5
    #spec_ngram_simple_size_n=10
    #spec_ngram_simple_min_hits=1

    pi_agent_model: >
        { 
            "_test": "?",
            "id": "OpenAI-20B-NEO-CODE2-Plus-Uncensored-IQ4_NL_davidau.gguf",
            "name": "OpenAI-20B-NEO-CODE2_IQ4_NL",            
            "contextWindow": 131072,
            "maxTokens": 4096,
            "reasoning": true
        },

